/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddWeightModal: typeof import('./src/components/AddWeightModal.vue')['default']
    AddWorkoutEntryModal: typeof import('./src/components/AddWorkoutEntryModal.vue')['default']
    AddWorkoutModal: typeof import('./src/components/AddWorkoutModal.vue')['default']
    ArchiveProgramModal: typeof import('./src/components/ArchiveProgramModal.vue')['default']
    LoadingModal: typeof import('./src/components/LoadingModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpperNavBar: typeof import('./src/components/UpperNavBar.vue')['default']
    WeightGraph: typeof import('./src/components/WeightGraph.vue')['default']
    WeightTable: typeof import('./src/components/WeightTable.vue')['default']
    WorkoutEntriesTable: typeof import('./src/components/WorkoutEntriesTable.vue')['default']
    WorkoutGraph: typeof import('./src/components/WorkoutGraph.vue')['default']
    WorkoutTable: typeof import('./src/components/WorkoutTable.vue')['default']
  }
}
