services:
  gainsmith:
    image: gloof11/gainsmith
    restart: unless-stopped
    container_name: gainsmith
    ports:
      - '8090:8090'
    environment:
      - SUPERUSER=${SUPERUSER:?SUPERUSER is required}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD:?SUPERUSER_PASSWORD is required}
    volumes:
      - ./pb_data:/app/pb_data
