services:
  gainsmith:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./pb/pb_data:/pb/pb_data
      - ./pb/pb_migrations:/pb/pb_migrations
